### ISSUE TITLE
Bug: automated tests: Test fails on windows node 6

### ISSUE THREAD

**Issue by tpraxl** [tpraxl/laravel-mix#3]
The AppVeyor test for node 6 fails, because the generated md5 version hash of `vendor.js` is `c661c10a14f50393f6c0` instead of the expected `00515c3c8da75e02c556`.

Maybe this has to do with `fs.readFileSync` and line endings. Maybe not.

Interestingly enough, the other files' hashes are just as expected.

**Comment by tpraxl** [comment]
Just as a reference: this `vendor.js` has been generated with a docker container based on `node:8.9.3-alpine`:

[content-of-vendor-js.txt](https://github.com/tpraxl/laravel-mix/files/1647424/content-of-vendor-js.txt)

**Comment by tpraxl** [comment]
@kohenkatz And here is the difference of what node6 reads and what node7 reads on windows. The whole log without the timestamps formatted as patch:

[node6-log-vs-node7-log.txt](https://github.com/tpraxl/laravel-mix/files/1647467/node6-log-vs-node7-log.txt)

[Edit] Actually, this was node 6 vs node 8

**Comment by tpraxl** [comment]
I think the following is happening: 

## node 6
It uses npm version 3.10.10. This version pulls the latest vue version within the defined range:  v2.5.13

## node 8 
[Edit, accidently focused on node 7, but it actually was node 8]
It uses npm version 5.6.0. This version pulls the vue version stored in `package.lock`: v2.5.8.

Vue will be extracted to `vendor.js` (even if it is not required anywhere in the fixtures). And because we have two different versions, the content differs, which correctly produces different hashes.

This doesn't happen in travis, because travis seems to use yarn…

But anyway: A test like this will fail over and over again. I think it should be changed to be less specific about the hashes.

**Comment by kohenkatz** [comment]
Interesting...

**Comment by kohenkatz** [comment]
Thinking about it, I do think that having the correct hash is important, because part of the test is knowing that the correct output is in each file and a hash is the easiest way to do that. I think that it is important to keep that check.

**Comment by tpraxl** [comment]
I'm not sure. It would be helpful if the test was not named "the kitchen sink". Maybe we should ask @JeffreyWay about his intentions for this test.

Let's say the hashes are important: do you have any ideas how to handle this?

**Comment by tpraxl** [comment]
I'm currently testing the following change: use yarn instead of npm. Seems to work fine, I just want to wait until the builds pass and will then merge it.

**Comment by tpraxl** [comment]
Switching to yarn for AppVeyor builds resolved the node6 problem. Now, the only remaining issue is randomly failing tests.

**Comment by kohenkatz** [comment]
@tpraxl If using Yarn is the easiest way of making sure the tests are consistent, the using Yarn is probably the best option.
